# Generated by Django 2.2 on 2022-03-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name="Autor's name")),
                ('last_name', models.CharField(max_length=100, verbose_name="Autor's last name")),
                ('facebook', models.URLField(null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(null=True, verbose_name='Instagram')),
                ('web', models.URLField(null=True, verbose_name='Web')),
                ('state', models.BooleanField(default=True, verbose_name='state of the autor')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create Date')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name of the category')),
                ('state', models.BooleanField(default=True, verbose_name='State of the category')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
