# Generated by Django 2.2 on 2022-03-25 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Content')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('image', models.URLField(max_length=255)),
                ('state', models.BooleanField(default=True, verbose_name='Post/No post')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.Autor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.Category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
